name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GHC
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.4.0.0"

      - name: Install dependencies
        run: cabal update

      - name: Build project
        run: cabal build

      - name: Create source distribution
        run: cabal sdist

      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: json-to-sql
          path: dist-newstyle/sdist/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download source distribution
        uses: actions/download-artifact@v2
        with:
          name: json-to-sql

      - name: Calculate SHA256 checksum
        id: sha256
        run: |
          tarball=$(ls json-to-sql-*.tar.gz)
          sha256sum $tarball > sha256.txt
          echo "::set-output name=sha256::$(cut -d' ' -f1 sha256.txt)"

      - name: Create release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            SHA256 checksum: ${{ steps.sha256.outputs.sha256 }}
          artifacts: json-to-sql-*.tar.gz
