name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Haskell dependencies (Cabal packages)
        uses: actions/cache@v4
        with:
          path: |
            ~/.ghc
            ~/.cabal
          key: ${{ runner.os }}-ghc-cabal-${{ hashFiles('**/*.cabal', '**/cabal.config') }}
          restore-keys: |
            ${{ runner.os }}-ghc-cabal-

      - name: Install Homebrew on macOS
        if: runner.os == 'macOS'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install LLVM on macOS
        if: runner.os == 'macOS'
        run: brew install llvm
        env:
          PATH: /usr/local/opt/llvm/bin:$PATH

      - name: Set up Haskell (GHC & Cabal)
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.12.1.0"

      - name: Install dependencies
        run: cabal update

      - name: Build executable on Linux or macOS
        if: runner.os != 'Windows'
        run: |
          cabal build
          mkdir -p dist
          BIN_PATH=$(cabal list-bin json-to-sql-exe)
          if [[ -f "$BIN_PATH" ]]; then
            cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
          else
            echo "Error: Executable not found!"
            exit 1
          fi

      - name: Build executable on Windows
        if: runner.os == 'Windows'
        run: |
          cabal build
          mkdir -p dist
          BIN_PATH=$(cabal list-bin json-to-sql-exe)
          if (Test-Path $BIN_PATH) {
            Copy-Item $BIN_PATH dist/json-to-sql-windows.exe
          } else {
            Write-Error "Error: Executable not found!"
            exit 1
          }

      - name: Upload built executables
        uses: actions/upload-artifact@v4
        with:
          name: json-to-sql-${{ runner.os }}
          path: dist/*
