name: Build and Release JSON-to-SQL

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell (GHC & Cabal)
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.4.0.0"

      - name: Install dependencies
        run: cabal update

      - name: Build executable
        run: |
          cabal build
          mkdir -p dist
          BIN_PATH=$(cabal list-bin json-to-sql-exe)
          if [[ -f "$BIN_PATH" ]]; then
            cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
          else
            echo "Error: Executable not found!"
            exit 1
          fi

      - name: Upload built executables
        uses: actions/upload-artifact@v4
        with:
          name: json-to-sql-${{ runner.os }}
          path: dist/*
