name: Build and Release JSON-to-SQL

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Haskell dependencies (Cabal packages)
        uses: actions/cache@v4
        with:
          path: |
            ~/.ghc
            ~/.cabal
          key: ${{ runner.os }}-ghc-cabal-${{ hashFiles('**/*.cabal', '**/cabal.config') }}
          restore-keys: |
            ${{ runner.os }}-ghc-cabal-

      - name: Install LLVM on macOS
        if: runner.os == 'macOS'
        run: brew install llvm@12
        env:
          PATH: /usr/local/opt/llvm@12/bin:$PATH

      - name: Set up Haskell (GHC & Cabal)
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.4.0.0"

      - name: Install dependencies
        run: cabal update

      - name: Build executable
        run: |
          cabal build
          mkdir -p dist
          BIN_PATH=$(cabal list-bin exe:json-to-sql)
          if [[ -f "$BIN_PATH" ]]; then
            cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
          else
            echo "Error: Executable not found!"
            exit 1
          fi

      - name: Upload built executables
        uses: actions/upload-artifact@v4
        with:
          name: json-to-sql-${{ runner.os }}
          path: dist/*
